#!/usr/bin/env python3
"""Generiert assets/data/daily_hadith_library.json (Schema v3, ~90 Hadithe)."""

from __future__ import annotations

import json
from pathlib import Path

# (id, referenceDe, sunnah_slug, textDe, textAr, einordnungDe, tags, season, fridayOk, tier)
HADITHS: list[tuple] = [
    (1, "Sahih al-Bukhari 1", "bukhari:1",
     "Die Taten werden nur nach den Absichten bewertet, und jeder Mensch erhält nur das, was er beabsichtigt hat.",
     "إنما الأعمال بالنيات",
     "Viele Sammlungen beginnen mit dieser Überlieferung: Allah sieht zuerst das Herz und die Absicht — nicht nur das Äußere.",
     ["niyya", "grundlage"], ["all"], True, 1),
    (2, "Sahih al-Bukhari 2", "bukhari:2",
     "Wer seine Heimat verlässt um Allah und Seinen Gesandten und dann stirbt, noch bevor er ausgewandert ist, dem wird doch der Lohn des Ausgewanderten zuteil.",
     "",
     "Es geht um aufrichtigen Entschluss: schon der Weg und die Absicht zählen — auch wenn man das Ziel nicht mehr erreicht.",
     ["niyya", "hidschra"], ["all"], True, 2),
    (3, "Sahih Muslim 8a", "muslim:8a",
     "Der Islam baut auf fünf Säulen: dem Zeugnis, dass es keinen Gott gibt außer Allah, dem Gebet, der Zakah, der Pilgerfahrt und dem Fasten im Ramadan.",
     "بُنِيَ الإِسْلامُ عَلَى خَمْسٍ",
     "Ein Grundriss des Glaubens — gut, um zu prüfen, was man schon lebt und was man vertiefen möchte.",
     ["iman", "islam", "grundlage"], ["all"], True, 1),
    (4, "Sahih al-Bukhari 8", "bukhari:8",
     "Die Religion ist aufrichtiger Rat — gegenüber Allah, Seinem Buch, Seinem Gesandten, den Führern der Muslime und der Gemeinschaft.",
     "الدين النصيحة",
     "Aufrichtigkeit umfasst auch ehrliche Selbstkritik — gegenüber Allah, Qur’an und der Ummah.",
     ["nasihah", "gemeinschaft"], ["all"], True, 1),
    (5, "Sahih Muslim 40a", "muslim:40a",
     "Wer in unserer Angelegenheit etwas Neues einführt, was nicht dazugehört, wird zurückgewiesen.",
     "من أحدث في أمرنا هذا ما ليس منه فهو رد",
     "Gemeint sind religiöse Neuerungen ohne Grundlage in Qur’an und bewährter Sunna — nicht jede Alltagserfindung.",
     ["sunna", "grundlage"], ["all"], False, 2),
    (6, "Sahih Muslim 45a", "muslim:45a",
     "Keiner von euch glaubt wirklich, bis er für seinen Bruder liebt, was er für sich selbst liebt.",
     "لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه",
     "Echter Glaube zeigt sich in Bruderlichkeit — im Kleinen üben, Neid und Egoismus ablegen.",
     ["bruderlichkeit", "akhlak"], ["all"], True, 1),
    (7, "Sahih Muslim 1053", "muslim:1053",
     "Hütet euch vor dem Feuer, und wenn es nur mit einem halben Dattelstück ist, das ihr im Weg Allahs gebt.",
     "اتقوا النار ولو بشق تمرة",
     "Schon kleine Aufrichtigkeit zählt — es geht um Aufrichtigkeit, nicht um den Betrag.",
     ["spende", "aufrichtigkeit"], ["all"], True, 1),
    (8, "Jami' at-Tirmidhi 2646", "tirmidhi:2646",
     "Wer einen Weg geht, um Wissen zu erlangen, dem ebnet Allah einen Weg zum Paradies.",
     "",
     "Lernen um Qur’an und Sunna ist kein Extra für Gelehrte — Schritt für Schritt, mit Geduld.",
     ["wissen", "quran"], ["all"], True, 1),
    (9, "Sahih Muslim 1631", "muslim:1631",
     "Der Muslim ist derjenige, vor dessen Zunge und Hand andere Muslime in Sicherheit sind.",
     "المسلم من سلم المسلمون من لسانه ويده",
     "Ein Maßstab für Umgang: auch online keine Verletzung durch Worte oder Druck.",
     ["zunge", "akhlak"], ["all"], True, 1),
    (10, "Sahih al-Bukhari 42", "bukhari:42",
     "Wer keine Barmherzigkeit zeigt, dem wird keine Barmherzigkeit gezeigt.",
     "من لا يرحم لا يرحم",
     "Barmherzigkeit wirkt wie ein Spiegel — in Familie und Nachbarschaft spürbar.",
     ["barmherzigkeit", "akhlak"], ["all"], True, 1),
    (11, "Sahih al-Bukhari 13", "bukhari:13",
     "Von den Besten unter euch sind diejenigen, die den besten Charakter haben.",
     "",
     "Guter Charakter ist kein Nebenthema — er gehört zum Kern des Islam im Alltag.",
     ["akhlak", "charakter"], ["all"], True, 1),
    (12, "Sahih al-Bukhari 5027", "bukhari:5027",
     "Der Beste unter euch ist der, der den Qur’an lernt und ihn lehrt.",
     "خيركم من تعلم القرآن وعلمه",
     "Lernen und Weitergeben gehören zusammen — auch eine Ayah an Kinder oder Freunde.",
     ["quran", "wissen"], ["all"], True, 1),
    (13, "Sahih al-Bukhari 6014", "bukhari:6014",
     "Vermeidet den Verdacht: denn Verdacht ist die lügenhafteste Rede. Spioniert nicht, führt keine Ränke gegeneinander und hasst euch nicht.",
     "",
     "Gerüchte und Misstrauen zerstören Gemeinschaft — lieber nachfragen als vermuten.",
     ["zunge", "gemeinschaft"], ["all"], True, 1),
    (14, "Sahih Muslim 54", "muslim:54",
     "Ihr werdet das Paradies nicht betreten, bis ihr glaubt, und ihr werdet nicht glauben, bis ihr einander liebt. Soll ich euch etwas nennen, das, wenn ihr es tut, euch lieben lässt? Verbreitet den Salam unter euch.",
     "أفلا أدلكم على شيء إذا فعلتموه تحاببتم",
     "Der Salam ist mehr als Höflichkeit — er öffnet Herzen und baut Vertrauen auf.",
     ["salam", "bruderlichkeit"], ["all"], True, 1),
    (15, "Sahih al-Bukhari 11", "bukhari:11",
     "Keiner von euch glaubt wirklich, bis ich ihm lieber bin als sein Vater, sein Kind und alle Menschen.",
     "",
     "Liebe zum Propheten ordnet Prioritäten neu — ohne Familie zu vernachlässigen, sondern im Licht der Sunna.",
     ["iman", "prophet"], ["all"], True, 2),
    (16, "Sahih Muslim 223", "muslim:223",
     "Reinheit ist die Hälfte des Glaubens.",
     "الطهور شطر الإيمان",
     "Wudu und Sauberkeit verbinden Körper und Herz — eine kleine Vorbereitung vor dem Gebet.",
     ["reinheit", "salat"], ["all"], True, 1),
    (17, "Sahih al-Bukhari 527", "bukhari:527",
     "Allah hat euch das Gebet auferlegt; wer es pflegt, bewahrt es, und wer es verachtet, dem wird kein Anteil am Schutz Allahs zugesichert.",
     "",
     "Das Gebet ist Vertrag mit Allah — regelmäßigkeit wichtiger als Perfektion beim ersten Mal.",
     ["salat", "pflicht"], ["all"], True, 1),
    (18, "Sahih Muslim 82", "muslim:82",
     "Der Glaube besteht aus über siebzig Zweigen; der höchste ist das Zeugnis, dass es keinen Gott gibt außer Allah, und der niedrigste ist, etwas Schädliches vom Weg zu entfernen. Die Schamhaftigkeit gehört zum Glauben.",
     "",
     "Glaube ist breit: von der Shahada bis zu kleinen Taten der Rücksicht im Alltag.",
     ["iman", "schamhaftigkeit"], ["all"], True, 1),
    (19, "Sahih al-Bukhari 6464", "bukhari:6464",
     "Wer an Allah und den Jüngsten Tag glaubt, soll Gutes sprechen oder schweigen.",
     "من كان يؤمن بالله واليوم الآخر فليقل خيرا أو ليصمت",
     "Worte haben Gewicht — besonders in Wut oder in Gruppenchats.",
     ["zunge", "akhlak"], ["all"], True, 1),
    (20, "Sahih Muslim 45", "muslim:45",
     "Keiner von euch glaubt wirklich, bis er für seinen Bruder liebt, was er für sich selbst liebt — und bis er ihm dasselbe wünscht, was er sich selbst wünscht.",
     "",
     "Bruderlichkeit konkret: Gutes für andere wünschen wie für sich selbst.",
     ["bruderlichkeit"], ["all"], True, 1),
    (21, "Sahih al-Bukhari 6116", "bukhari:6116",
     "Der Starke ist nicht der, der im Ringkampf siegt, sondern der, der sich beherrscht, wenn er wütend ist.",
     "ليس الشديد بالصرعة",
     "Wut ist eine Prüfung — Pause, Dua und Weggehen können mehr Stärke zeigen als laut werden.",
     ["wut", "sabr", "akhlak"], ["all"], True, 1),
    (22, "Sahih Muslim 2586", "muslim:2586",
     "Wer an Allah und den Jüngsten Tag glaubt, soll seinen Gast ehren.",
     "",
     "Gastfreundschaft stärkt Bande — auch ein einfaches Essen oder ein ehrlicher Empfang.",
     ["gastfreundschaft", "adab"], ["all"], True, 1),
    (23, "Sahih al-Bukhari 6018", "bukhari:6018",
     "Wer an Allah und den Jüngsten Tag glaubt, soll seinen Nachbarn nicht schaden.",
     "",
     "Der Nachbar hat Rechte — Lärm, Rauch oder Gleichgültigkeit können schon genügen, um sie zu verletzen.",
     ["nachbar", "adab"], ["all"], True, 1),
    (24, "Sahih Muslim 2625", "muslim:2625",
     "Allah liebt, wenn einer von euch etwas tut, dass er es ordentlich tut.",
     "إن الله يحب إذا عمل أحدكم عملا أن يتقنه",
     "Ihsan im Kleinen: Gebet, Arbeit, Hilfe — Qualität als Form von Gottesfurcht.",
     ["ihsan", "aufrichtigkeit"], ["all"], True, 1),
    (25, "Sahih al-Bukhari 52", "bukhari:52",
     "Das Erlaubte ist klar und das Verbotene ist klar; zwischen beiden liegen zweifelhafte Dinge, die viele nicht kennen.",
     "الحلال بين والحرام بين",
     "Bei Unsicherheit lieber nachfragen oder zurückhalten — Vorsicht schützt den Glauben.",
     ["fiqh", "vorsicht"], ["all"], False, 2),
    (26, "Jami' at-Tirmidhi 2318", "tirmidhi:2318",
     "Von der Vollkommenheit des Islam eines Menschen ist es, dass er lässt, was ihn nichts angeht.",
     "من حسن إسلام المرء تركه ما لا يعنيه",
     "Weniger Tratsch, weniger Neugier auf Privates — mehr Energie für das, was Allah liebt.",
     ["zunge", "adab"], ["all"], True, 1),
    (27, "Sahih Muslim 2699", "muslim:2699",
     "Der Diener sagt: Mein Herr! Mein Herr! — doch Allah fragt: Hast du mir etwas vorgesetzt, das ich dir vergelten soll, oder hast du nur deinen Mund gebraucht, während dein Herz abwesend war?",
     "",
     "Aufrichtigkeit im Dua: nicht nur Worte, sondern Vertrauen und Demut.",
     ["dua", "aufrichtigkeit"], ["all"], True, 1),
    (28, "Sahih al-Bukhari 6405", "bukhari:6405",
     "Ruft Allah an, während ihr Gewissheit habt, und wisset, dass Allah nicht das Gebet eines Herzens annimmt, das zerstreut und leichtfertig ist.",
     "",
     "Kurze Momente echter Anrufung sind wertvoller als lange Worte ohne Gegenwart.",
     ["dua", "tawakkul"], ["all"], True, 1),
    (29, "Sahih Muslim 2731", "muslim:2731",
     "Es gibt keinen Muslim, der Allah um etwas bittet, bei dem keine Sünde oder kein Familienbruch ist, ohne dass Allah ihm eine von drei Gaben gibt: bald erhören, Schaden davon abwenden oder für das Jenseits aufheben.",
     "",
     "Dua wird gehört — auch wenn die Antwort anders aussieht, als wir erwarten.",
     ["dua", "tawakkul"], ["all"], True, 1),
    (30, "Sahih al-Bukhari 6306", "bukhari:6306",
     "Wer sich auf Allah verlässt, dem genügt Er.",
     "ومن يتوكل على الله فهو حسبه",
     "Tawakkul ist keine Passivität — man tut sein Bestes und übergibt den Rest.",
     ["tawakkul", "sabr"], ["all"], True, 1),
    (31, "Sahih Muslim 2999", "muslim:2999",
     "Wunderbar ist die Angelegenheit des Gläubigen: Alles ist gut für ihn — und das gilt nur für den Gläubigen. Freut er sich, dankt er; trifft ihn Leid, ist er geduldig.",
     "",
     "Schwierige Tage können durch Dankbarkeit und Sabr eine andere Farbe bekommen.",
     ["sabr", "shukr"], ["all"], True, 1),
    (32, "Sahih Muslim 91e", "muslim:91e",
     "Allah ist schön und liebt die Schönheit.",
     "إن الله جميل يحب الجمال",
     "Sauberkeit, ordentliche Kleidung und schöne Worte — ohne Prahlerei oder Verschwendung.",
     ["adab", "ihsan"], ["all"], True, 1),
    (33, "Sahih al-Bukhari 5645", "bukhari:5645",
     "Wer unter den Menschen am meisten Dank gegenüber Allah zeigt, der dankt auch den Menschen am meisten.",
     "",
     "Dankbarkeit beginnt bei Allah und zeigt sich in kleinen Worten gegenüber anderen.",
     ["shukr", "akhlak"], ["all"], True, 1),
    (34, "Sahih al-Bukhari 6416", "bukhari:6416",
     "Seid in dieser Welt, als wärt ihr ein Fremder oder ein Reisender.",
     "كن في الدنيا كأنك غريب أو عابر سبيل",
     "Besitz und Status sind vorübergehend — was bleibt, sind gute Taten und ein reines Herz.",
     ["besinnung", "welt"], ["all"], True, 1),
    (35, "Sahih al-Bukhari 5649", "bukhari:5649",
     "Wer nicht den Menschen dankt, dankt nicht Allah.",
     "",
     "Ein ehrliches Danke an Eltern, Partner oder Kollegen ist Teil des Glaubens.",
     ["shukr"], ["all"], True, 1),
    (36, "Sahih Muslim 2577", "muslim:2577",
     "Allah freut sich über die Reue Seines Dieners mehr als über einen, der in der Wüste sein Kamel verliert und es dann wiederfindet.",
     "",
     "Reue ist kein Ende, sondern Rückkehr — Allah nimmt sie an, wenn sie aufrichtig ist.",
     ["reue", "hoffnung"], ["all"], True, 1),
    (37, "Sahih al-Bukhari 6307", "bukhari:6307",
     "Bei Allah ist die Reue des Dieners angenehmer als die Freude dessen, der in der Wüste sein Reittier verliert und es wiederfindet.",
     "",
     "Keine Sünde ist zu groß für aufrichtige Reue — der erste Schritt zählt.",
     ["reue"], ["all"], True, 1),
    (38, "Sahih Muslim 2747", "muslim:2747",
     "Allah neigt sich in der letzten Nacht des Ramadan zu Seiner Schöpfung und vergibt allen außer dem Götzendiener und dem, der Zwietracht stiftet.",
     "",
     "Laylat al-Qadr und die letzten Ramadan-Nächte laden zu aufrichtiger Bitte und Versöhnung ein.",
     ["ramadan", "vergebung"], ["all", "ramadan"], True, 1),
    (39, "Sahih al-Bukhari 1901", "bukhari:1901",
     "Wenn der Ramadan beginnt, werden die Tore des Paradieses geöffnet, die Tore des Feuers geschlossen und die Teufel gefesselt.",
     "",
     "Der Monat ist eine Einladung zu mehr Gebet, Qur’an und innerer Sammlung.",
     ["ramadan"], ["all", "ramadan"], True, 1),
    (40, "Sahih Muslim 1079", "muslim:1079",
     "Wer im Ramadan aus Glauben und in Erwartung des Lohnes fastet, dem werden seine früheren Sünden vergeben.",
     "",
     "Fasten verbindet Hunger mit Bewusstsein — nicht nur Verzicht auf Essen.",
     ["ramadan", "fasten"], ["all", "ramadan"], True, 1),
    (41, "Sahih al-Bukhari 6", "bukhari:6",
     "Der Islam wurde auf fünf Säulen errichtet: Zeugnis, Gebet, Zakah, Fasten im Ramadan und Hajj.",
     "",
     "Die fünf Säulen sind ein Kompass — nicht alles auf einmal perfekt, aber bewusst leben.",
     ["islam", "ramadan"], ["all", "ramadan"], True, 1),
    (42, "Sahih Muslim 1151", "muslim:1151",
     "Das Fasten ist ein Schutzschild. An einem Tag, an dem einer von euch fastet, soll er weder schlecht reden noch lärmen; wenn jemand ihn beleidigt, soll er sagen: Ich faste.",
     "",
     "Fasten betrifft Zunge und Verhalten — nicht nur den Magen.",
     ["ramadan", "fasten", "zunge"], ["all", "ramadan"], True, 1),
    (43, "Sahih al-Bukhari 5927", "bukhari:5927",
     "Wer fastet, hat zwei Freuden: wenn er bricht, freut er sich über das Fastenbrechen, und wenn er seinen Herrn trifft, freut er sich über sein Fasten.",
     "",
     "Die innere Freude am Fasten bleibt — eine Erinnerung an Allahs Nähe.",
     ["ramadan", "fasten"], ["all", "ramadan"], True, 1),
    (44, "Sahih Muslim 6", "muslim:6",
     "Der Glaube ist, dass du an Allah, Seine Engel, Seine Bücher, Seine Gesandten und den Jüngsten Tag glaubst, und an die Vorbestimmung — Gutes wie Schlechtes.",
     "",
     "Die sechs Glaubensartikel ordnen das Herz — auch wenn man manches erst nach und nach begreift.",
     ["iman", "grundlage"], ["all"], True, 1),
    (45, "Sahih al-Bukhari 50", "bukhari:50",
     "Wer glaubt an Allah und den Jüngsten Tag, soll seinen Gast ehren; wer glaubt, soll seinen Nachbarn nicht schaden; wer glaubt, soll, wenn er spricht, Gutes sagen oder schweigen.",
     "",
     "Glaube zeigt sich in drei Alltagsbereichen: Gäste, Nachbarn, Worte.",
     ["iman", "adab"], ["all"], True, 1),
    (46, "Sahih Muslim 2567", "muslim:2567",
     "Lest den Qur’an, denn er wird am Tag der Auferstehung als Fürsprecher für die kommen, die ihn gelesen haben.",
     "",
     "Schon wenige Verse regelmäßig können mehr bewirken als selten viel auf einmal.",
     ["quran"], ["all"], True, 1),
    (47, "Sahih al-Bukhari 5027", "bukhari:5027",
     "Der Qur’an wird am Jüngsten Tag für den sprechen, der ihn gelesen hat.",
     "",
     "Die Verbindung zum Buch ist eine Investition — mit Geduld und ohne Druck.",
     ["quran"], ["all"], True, 1),
    (48, "Sahih Muslim 782", "muslim:782",
     "Die ersten Dinge, über die der Mensch gerichtet wird, sind sein Gebet.",
     "",
     "Das Gebet steht im Zentrum — Verbesserung Schritt für Schritt ist besser als Aufgeben.",
     ["salat", "jenseits"], ["all"], True, 1),
    (49, "Sahih al-Bukhari 528", "bukhari:528",
     "Das Gebet ist das Erste, wofür der Diener zur Rechenschaft gezogen wird.",
     "",
     "Wer sein Gebet verbessert, hat viel gewonnen — wer es vernachlässigt, hat viel verloren.",
     ["salat"], ["all"], True, 1),
    (50, "Sahih Muslim 223", "muslim:223",
     "Die Reinheit ist die Hälfte des Glaubens, und das Preisen Allahs füllt die Waage.",
     "",
     "Wudu vor dem Gebet kann den Kopf vom Alltag lösen und das Herz sammeln.",
     ["reinheit", "dhikr"], ["all"], True, 1),
    (51, "Sahih al-Bukhari 1124", "bukhari:1124",
     "Das Freitagsgebet ist eine Pflicht für jeden Muslim — ausgenommen Sklaven, Frauen, Kinder und Reisende.",
     "",
     "Der Jumuʿah ist ein wöchentlicher Anker der Gemeinschaft — auch wenn man manchmal müde ist.",
     ["freitag", "gemeinschaft", "salat"], ["all"], True, 1),
    (52, "Sahih Muslim 856", "muslim:856",
     "An einem Freitag gibt es eine Stunde, in der kein gläubiger Diener betet, ohne dass Allah ihm gibt, worum er bittet.",
     "",
     "Am Freitag bewusst Dua machen — besonders nach Asr, wie viele Gelehrte lehren.",
     ["freitag", "dua"], ["all"], True, 1),
    (53, "Sahih al-Bukhari 917", "bukhari:917",
     "Wer am Freitag gut badet, sich parfumiert, wenn er es hat, und die Moschee aufsucht ohne Trennung, und schweigt, bis der Imam aus ist — dem werden seine Sünden zwischen zwei Freitagen vergeben.",
     "",
     "Freitag als kleine wöchentliche Erneuerung — Vorbereitung zählt.",
     ["freitag", "reue"], ["all"], True, 1),
    (54, "Sahih Muslim 2333", "muslim:2333",
     "Die besten Tage, an denen die Sonne aufgeht, sind die zehn Tage von Dhu l-Hiddscha.",
     "",
     "In den ersten zehn Tagen des Pilgermonats: mehr Tasbih, Tahmid und gute Taten.",
     ["dhul_hijjah"], ["all", "dhul_hijjah"], True, 1),
    (55, "Sahih al-Bukhari 969", "bukhari:969",
     "Es gibt keinen Tag, an dem Allah mehr Diener aus dem Feuer befreit als am Tag des Opferfestes.",
     "",
     "Das Opferfest verbindet Opferbereitschaft, Dank und Gemeinschaft.",
     ["dhul_hijjah", "opfer"], ["all", "dhul_hijjah"], True, 1),
    (56, "Sahih Muslim 1162", "muslim:1162",
     "Nehmt euch einen Anteil vom Hajj: die Umra.",
     "",
     "Auch wer nicht pilgern kann, kann sich mit Hajj und Umra vertraut machen und dafür bitten.",
     ["hajj"], ["all"], True, 1),
    (57, "Sahih al-Bukhari 1519", "bukhari:1519",
     "Wer den Hajj vollzieht, ohne Unanständiges oder Sünde, kehrt zurück wie am Tag, an dem seine Mutter ihn geboren hat.",
     "",
     "Hajj ist Reinigung — für die, die gehen können, eine einmalige Lebensreise.",
     ["hajj"], ["all"], False, 2),
    (58, "Sahih Muslim 1015", "muslim:1015",
     "Die Zakah ist eine Pflicht — sie reinigt Vermögen und Herzen.",
     "",
     "Zakah verbindet Reichtum mit Verantwortung — auch kleine regelmäßige Gaben im Geist der Pflicht.",
     ["zakat", "spende"], ["all"], True, 1),
    (59, "Sahih al-Bukhari 1395", "bukhari:1395",
     "Gib eine Almosensteuer, auch wenn es nur eine Handvoll Gerste ist.",
     "",
     "Es geht nicht nur um Summen — Aufrichtigkeit und Regelmäßigkeit.",
     ["zakat", "spende"], ["all"], True, 1),
    (60, "Sahih Muslim 2588", "muslim:2588",
     "Die rechte Hand soll nicht wissen, was die linke gibt.",
     "",
     "Heimliche Spende schützt vor Prahlerei und bewahrt die Aufrichtigkeit.",
     ["spende", "aufrichtigkeit"], ["all"], True, 1),
    (61, "Sahih al-Bukhari 1416", "bukhari:1416",
     "Der Unterstützer einer Witwe und der Armen gleicht dem, der im Weg Allahs kämpft oder wie der, der tagsüber fastet und nachts betet.",
     "",
     "Hilfe für Schwache ist großer Gottesdienst — oft näher als man denkt.",
     ["spende", "barmherzigkeit"], ["all"], True, 1),
    (62, "Sahih Muslim 2582", "muslim:2582",
     "Der Unterstützer einer Witwe hat die Belohnung dessen, der unablässig im Weg Allahs steht.",
     "",
     "Familien in Not praktisch unterstützen — Essen, Zeit oder Zuhören.",
     ["spende", "familie"], ["all"], True, 1),
    (63, "Sahih al-Bukhari 5971", "bukhari:5971",
     "Das Paradies liegt zu Füßen der Mütter.",
     "الجنة تحت أقدام الأمهات",
     "Der Umgang mit den Eltern ist ein direkter Weg zu Allahs Zufriedenheit.",
     ["familie", "eltern"], ["all"], True, 1),
    (64, "Sahih Muslim 2546", "muslim:2546",
     "Der Beste unter euch ist der Beste zu seiner Familie, und ich bin der Beste zu meiner Familie.",
     "",
     "Gutes Benehmen zu Partner und Kindern ist Maßstab des Charakters.",
     ["familie", "akhlak"], ["all"], True, 1),
    (65, "Sahih al-Bukhari 5991", "bukhari:5991",
     "Keiner von euch glaubt wirklich, bis er für seine Familie das Beste wünscht, was er für sich selbst wünscht.",
     "",
     "Fairness beginnt zu Hause — Gerechtigkeit zwischen Geschwistern und Kindern.",
     ["familie", "bruderlichkeit"], ["all"], True, 1),
    (66, "Sahih Muslim 1623", "muslim:1623",
     "Der Glaube hat über sechzig Äste; das Höchste ist: Es gibt keinen Gott außer Allah, das Niedrigste ist, etwas Schädliches vom Weg zu entfernen, und die Schamhaftigkeit ist ein Ast des Glaubens.",
     "",
     "Schamhaftigkeit schützt Herz und Blick — ein Zeichen von Würde.",
     ["iman", "schamhaftigkeit"], ["all"], True, 1),
    (67, "Sahih al-Bukhari 6114", "bukhari:6114",
     "Schamhaftigkeit bringt nur Gutes.",
     "الحياء لا يأتي إلا بخير",
     "Scham im guten Sinne ist keine Schwäche, sondern Reinheit.",
     ["schamhaftigkeit", "akhlak"], ["all"], True, 1),
    (68, "Sahih Muslim 35", "muslim:35",
     "Lasst mich euch vor dem größten der großen Sünden warnen: Shirk an Allah, Ungehorsam gegenüber den Eltern — und er setzte sich aufrecht hin und sagte: Und das falsche Zeugnis und das falsche Reden.",
     "",
     "Die schwersten Sünden betreffen Allah, Eltern und Wahrheit — bewusst machen hilft, sie zu meiden.",
     ["warnung", "eltern"], ["all"], False, 2),
    (69, "Sahih al-Bukhari 5970", "bukhari:5970",
     "Wer seine Eltern ehrt, dem wird sein Kind ehren; wer sie entehrt, dem wird sein Kind entehren.",
     "",
     "Wie wir mit Eltern umgehen, prägt oft die nächste Generation.",
     ["eltern", "familie"], ["all"], True, 1),
    (70, "Sahih Muslim 2564", "muslim:2564",
     "Keiner von euch glaubt wirklich, bis er für seinen Bruder liebt, was er für sich liebt.",
     "",
     "Eifersucht aufbricht, wenn man dem anderen Gutes wünscht — bewusst üben.",
     ["bruderlichkeit"], ["all"], True, 1),
    (71, "Sahih al-Bukhari 2442", "bukhari:2442",
     "Keiner von euch glaubt wirklich, bis er für seinen Bruder liebt, was er für sich liebt.",
     "",
     "Bruderlichkeit ist tägliche Arbeit — nicht nur in der Moschee.",
     ["bruderlichkeit"], ["all"], True, 1),
    (72, "Sahih Muslim 2560", "muslim:2560",
     "Der Gläubige mit dem Gläubigen ist wie ein Gebäude, dessen Teile einander stützen.",
     "مثل المؤمنين في توادهم",
     "Die Ummah trägt einander — auch ein Anruf oder eine Hilfe im Alltag.",
     ["gemeinschaft", "bruderlichkeit"], ["all"], True, 1),
    (73, "Sahih al-Bukhari 6011", "bukhari:6011",
     "Die Gläubigen in ihrer gegenseitigen Liebe, Barmherzigkeit und Mitleid sind wie ein Körper: Wenn ein Glied leidet, leidet der ganze Körper mit Fieber und Schlaflosigkeit.",
     "",
     "Empathie für Muslime weltweit — ohne Hetze, mit Dua und konkreter Hilfe wo möglich.",
     ["gemeinschaft", "barmherzigkeit"], ["all"], True, 1),
    (74, "Sahih Muslim 2586", "muslim:2586",
     "Besucht einander, liebt einander, seid Brüder.",
     "",
     "Freundschaft im Glauben braucht Pflege — nicht nur Likes, sondern echte Zeit.",
     ["gemeinschaft"], ["all"], True, 1),
    (75, "Sahih al-Bukhari 13", "bukhari:13",
     "Ich wurde gesandt, um vollendeten guten Charakter zu vollenden.",
     "",
     "Der Prophet ﷺ bringt Moral auf die Spitze — Höflichkeit, Ehrlichkeit, Geduld.",
     ["akhlak", "prophet"], ["all"], True, 1),
    (76, "Sahih Muslim 746a", "muslim:746a",
     "Die Barmherzigkeit wird nur den Barmherzigen gezeigt. Erbarmt euch derer auf der Erde, damit Der im Himmel Sich eurer erbarmt.",
     "ارحموا من في الأرض يرحمكم من في السماء",
     "Mitgefühl öffnet Türen — zu Menschen und zu Allahs Barmherzigkeit.",
     ["barmherzigkeit"], ["all"], True, 1),
    (77, "Sahih al-Bukhari 5997", "bukhari:5997",
     "Wer kein Mitleid mit unseren Kleinen zeigt und unsere Alten nicht ehrt, ist nicht von uns.",
     "",
     "Kinder ernst nehmen, Ältere respektieren — das gehört zur Sunna des Umgangs.",
     ["familie", "barmherzigkeit"], ["all"], True, 1),
    (78, "Sahih Muslim 2599", "muslim:2599",
     "Wer einen Hund vor Durst rettet, dem vergibt Allah eine Sünde. Wer eine Katze füttert, dem vergibt Allah eine Sünde.",
     "",
     "Güte gegenüber Tieren lehrt Sanftmut — auch im Umgang mit Menschen.",
     ["barmherzigkeit"], ["all"], True, 1),
    (79, "Sahih al-Bukhari 2361", "bukhari:2361",
     "Wer ein Lebewesen tötet ohne rechtmäßigen Grund, dem wird es am Tag der Auferstehung vorgehalten.",
     "",
     "Verantwortung für das Leben — kein Spiel mit Schmerz.",
     ["verantwortung"], ["all"], False, 2),
    (80, "Sahih Muslim 1571", "muslim:1571",
     "Der Ehrliche, vertrauenswürdige Händler steht bei den Propheten, den Wahrhaftigen und den Märtyrern.",
     "",
     "Ehrlichkeit im Beruf ist Gottesdienst — kein Verkauf mit Tricks.",
     ["ehrlichkeit", "beruf"], ["all"], True, 1),
    (81, "Sahih al-Bukhari 33", "bukhari:33",
     "Die Wahrhaftigkeit führt zur Rechtschaffenheit, und die Rechtschaffenheit führt ins Paradies.",
     "",
     "Ein kleines Versprechen halten kann mehr sein als große Worte.",
     ["ehrlichkeit"], ["all"], True, 1),
    (82, "Sahih Muslim 2607", "muslim:2607",
     "Lüge führt zur Frevlerei, und Frevlerei führt ins Feuer.",
     "",
     "Weiße Lügen und Übertreibungen summieren sich — Wahrheit schützt das Herz.",
     ["ehrlichkeit", "zunge"], ["all"], True, 1),
    (83, "Sahih al-Bukhari 6474", "bukhari:6474",
     "Denkt oft an das, was den Genuss zerstört: der Tod.",
     "",
     "Memento mori ist keine Depressión — es ordnet Prioritäten und macht dankbar.",
     ["tod", "besinnung"], ["all"], False, 2),
    (84, "Sahih Muslim 2877", "muslim:2877",
     "Bereitet euch vor, bevor ihr gerufen werdet.",
     "",
     "Gutes tun, solange Gesundheit und Zeit da sind — nicht auf „später“ warten.",
     ["tod", "vorbereitung"], ["all"], False, 2),
    (85, "Sahih al-Bukhari 6412", "bukhari:6412",
     "Wenn der Sohn Adams stirbt, enden seine Taten — außer drei: laufende Sadaqah, nützliches Wissen oder ein rechtschaffenes Kind, das für ihn betet.",
     "",
     "Anhaltende Wirkung: Stiftung, Lehren, Kinder erziehen — Investition fürs Hier und Jenseits.",
     ["jenseits", "wissen"], ["all"], True, 1),
    (86, "Sahih Muslim 163", "muslim:163",
     "Wer einen Weg zum Lernen geht, dem wird der Weg ins Paradies erleichtert.",
     "",
     "Jede Ayah, die man versteht und lebt, ist ein Schritt.",
     ["wissen", "quran"], ["all"], True, 1),
    (87, "Sahih al-Bukhari 79", "bukhari:79",
     "Von Allah werden nur die Gelehrten unter Seinen Dienern gefürchtet.",
     "",
     "Wissen mit Demut — nicht um Recht zu haben, sondern um Allah zu dienen.",
     ["wissen"], ["all"], True, 1),
    (88, "Sahih al-Bukhari 6471", "bukhari:6471",
     "Keiner von euch glaubt wirklich, bis er für seinen Bruder liebt, was er für sich liebt.",
     "",
     "Der Bruder im Glauben — auch wenn man sich manchmal entfremdet hat, Gutes wünschen üben.",
     ["bruderlichkeit"], ["all"], True, 1),
    (89, "Sahih al-Bukhari 6408", "bukhari:6408",
     "Zwei Worte, leicht auf der Zunge, schwer in der Waage: Subhan Allah wa bihamdihi, Subhan Allah al-Azim.",
     "",
     "Tasbih zwischendurch — im Weg, beim Warten, vor dem Schlafen.",
     ["dhikr"], ["all"], True, 1),
    (90, "Sahih Muslim 2691", "muslim:2691",
     "Soll ich euch etwas nennen, das die Waagschalen am Jüngsten Tag schwer macht? Subhan Allah wa bihamdihi, Subhan Allah al-Azim — hundert Mal.",
     "",
     "Kleine Formeln mit großer Wirkung — Gewohnheit statt einmaliger Eile.",
     ["dhikr", "jenseits"], ["all"], True, 1),
]

# Kuratierte Rotationsreihenfolge: Grundlagen → Alltag → Charakter → Spende → Ramadan → Rest
ROTATION_ORDER = [
    1, 3, 4, 6, 44, 11, 12, 16, 17, 9, 10, 14, 19, 21, 24, 30, 31, 33, 36, 27,
    46, 48, 50, 8, 86, 87, 89, 7, 58, 60, 61, 63, 64, 65, 23, 22, 72, 73, 76, 77,
    38, 39, 40, 41, 42, 43, 51, 52, 53, 54, 55, 2, 5, 15, 18, 20, 25, 26, 28, 29,
    32, 34, 35, 37, 45, 47, 49, 56, 57, 59, 62, 66, 67, 68, 69, 70, 71, 74, 75, 78,
    79, 80, 81, 82, 83, 84, 85, 88, 90, 13,
]


def main() -> None:
    items = []
    for row in HADITHS:
        (id_, ref, slug, text_de, text_ar, einordnung, tags, season, friday_ok, tier) = row
        items.append({
            "id": id_,
            "referenceDe": ref,
            "sourceUrl": f"https://sunnah.com/{slug}",
            "textDe": text_de,
            "textAr": text_ar,
            "einordnungDe": einordnung,
            "tags": tags,
            "season": season,
            "fridayOk": friday_ok,
            "tier": tier,
        })

    # Eindeutige IDs prüfen
    ids = [i["id"] for i in items]
    assert len(ids) == len(set(ids)), f"Duplicate ids: {ids}"
    assert len(items) >= 70, f"Only {len(items)} hadiths"

    rot_set = set(ROTATION_ORDER)
    assert len(ROTATION_ORDER) == len(rot_set), "rotationOrder has duplicates"
    assert rot_set == set(ids), "rotationOrder must contain every id exactly once"

    # Rotation: alle IDs genau einmal
    out = {
        "schemaVersion": 3,
        "noRepeatDays": 30,
        "rotationOrder": ROTATION_ORDER,
        "items": sorted(items, key=lambda x: x["id"]),
    }

    root = Path(__file__).resolve().parents[1]
    target = root / "assets" / "data" / "daily_hadith_library.json"
    target.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(items)} hadiths to {target}")


if __name__ == "__main__":
    main()
